[tool.poetry]
name = "llm-decision-spec"
version = "0.1.0"
description = ""
authors = ["Ben0112358"]
readme = "README.md"
packages = [
  { include = "llm_decision_spec", from = "src" }
]
[tool.poetry.dependencies]
python = ">=3.12,<4.0"
python-dateutil = "^2.9.0.post0"


[tool.poetry.group.dev.dependencies]
pytest = ">=8.4.1,<10.0.0"
black = ">=25.1,<27.0"
flake8 = "^7.3.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79

[tool.flake8]
line-length = 79
